#!/usr/bin/env python3
"""Designs the stage-2 decimation filters of the narrowband build.

Stage 1 (firmware): 4th-order CIC, decimate by 16, 16 Msps -> 1 Msps.
Stage 2 (firmware): symmetric FIR at 1 Msps, decimate by R2 (2, 3 or 4). The FIR
also equalises the CIC passband droop, so the output is flat to the edge of
its passband.

Writes ../src/dsp_taps.h (Q15 coefficients) and prints the response.
Needs numpy and scipy.
"""
import sys, os
import numpy as np
from scipy.signal import firls, freqz

FS0 = 16e6
R1, NCIC = 16, 4
FS1 = FS0 / R1

# r2: (taps, passband edge Hz, stopband edge Hz, stopband weight)
DESIGNS = {
    2: (41, 200e3, 300e3, 12.0),
    3: (61, 133e3, 200e3, 12.0),
    4: (73, 100e3, 150e3, 12.0),
}


def cic_mag(f):
    f = np.asarray(f, dtype=float)
    with np.errstate(divide="ignore", invalid="ignore"):
        h = np.sin(np.pi * f * R1 / FS0) / (R1 * np.sin(np.pi * f / FS0))
    h = np.where(f == 0, 1.0, h)
    return np.abs(h) ** NCIC


def design(r2):
    taps, fp, fst, wstop = DESIGNS[r2]
    pts = np.linspace(0, fp, 17)
    bands, desired, weights = [], [], []
    for a, b in zip(pts[:-1], pts[1:]):
        bands += [a, b]
        desired += [1.0 / cic_mag(a), 1.0 / cic_mag(b)]
        weights.append(1.0)
    bands += [fst, FS1 / 2]
    desired += [0.0, 0.0]
    weights.append(wstop)
    h = firls(taps, bands, desired, weight=weights, fs=FS1)
    h /= h.sum()                       # unity gain at DC
    q = np.round(h * 32768).astype(int)
    assert abs(q).max() < 32768
    return q, fp, fst


def report(r2, q, fp, fst):
    h = q / 32768.0
    f = np.linspace(0, FS1 / 2, 20001)
    _, H = freqz(h, worN=f, fs=FS1)
    tot = np.abs(H) * cic_mag(f)
    pb = tot[f <= fp]
    sb = tot[f >= fst]
    # aliasing from the stage-1 images around k * FS1 into the passband
    worst_img = 0.0
    for k in (1, 2, 3):
        fi = np.linspace(k * FS1 - fp, k * FS1 + fp, 4001)
        _, Hi = freqz(h, worN=np.mod(fi, FS1), fs=FS1)
        worst_img = max(worst_img, np.max(np.abs(Hi) * cic_mag(fi)))
    print(f"R2={r2}: {len(q)} taps, output {FS1 / r2 / 1e3:.0f} ksps, passband +-{fp / 1e3:.0f} kHz")
    print(f"   passband ripple {20 * np.log10(pb.max()):+.2f} / {20 * np.log10(pb.min()):+.2f} dB")
    print(f"   stopband (>{fst / 1e3:.0f} kHz) worst {20 * np.log10(sb.max()):.1f} dB")
    print(f"   CIC image alias into passband worst {20 * np.log10(worst_img):.1f} dB")


def emit(path, designs):
    # The tables are shared by the two copies of dsp.c (one per core): the core 1 copy is built with DSP_TAPS_EXTERN and only
    # declares them. Internal RAM is tight.
    defs, decls = [], []

    def table(decl, body, comment=""):
        decls.append(comment + "extern " + decl + ";")
        defs.append(comment + decl + " = {\n" + body + "\n};\n")

    lines = ["/* Generated by tools/design_taps.py - do not edit. */",
             "#pragma once", "#include <stdint.h>", ""]
    for r2, (q, _, _) in designs.items():
        lines.append(f"#define DSP_TAPS_R2_{r2} {len(q)}")
        # PIE (SIMD) copies: row a holds the taps shifted up by a elements, zero padded to whole 8-lane
        # vectors, so a window that starts a elements past a 16-byte boundary can be read aligned.
        vecs = (7 + len(q) + 7) // 8
        lines.append(f"#define DSP_PIE_VECS_R2_{r2} {vecs}")
        table(f"const int16_t dsp_taps_r2_{r2}[{len(q)}]",
              "\n".join("    " + ", ".join(str(int(v)) for v in q[i:i + 8]) + "," for i in range(0, len(q), 8)))
        rows = []
        for a in range(8):
            row = [0] * a + [int(v) for v in q] + [0] * (vecs * 8 - a - len(q))
            rows.append("    {" + ", ".join(str(v) for v in row) + "},")
        table(f"const int16_t dsp_taps_pie_r2_{r2}[8][{vecs * 8}] __attribute__((aligned(16)))", "\n".join(rows))
    # The CIC (4th order, decimation R1) as a plain FIR over the input samples: the kernel (1+z^-1+...+z^-(R1-1))^4, 61
    # coefficients, sum R1^4, largest value 2736 (fits int16). For block j it multiplies the 64 samples x[16(j-3)..16j+15] in
    # time order, so the table is the kernel reversed and padded with three leading zeros: 64 entries, 16-byte aligned.
    kern = np.ones(1, dtype=np.int64)
    for _ in range(NCIC):
        kern = np.convolve(kern, np.ones(R1, dtype=np.int64))
    assert len(kern) == NCIC * (R1 - 1) + 1 and kern.max() < 32768
    rev = [0] * (4 * R1 - len(kern)) + [int(v) for v in kern[::-1]]
    table("const int16_t dsp_cic_taps[64] __attribute__((aligned(16)))",
          "\n".join("    " + ", ".join(str(v) for v in rev[i:i + 8]) + "," for i in range(0, 64, 8)),
          "/* CIC4/16 as a 64-tap FIR over x[16(j-3)..16j+15], oldest sample first */\n")
    lines += ["", "#ifdef DSP_TAPS_EXTERN", *decls, "#else", "", *defs, "#endif", ""]
    with open(path, "w") as fh:
        fh.write("\n".join(lines))


if __name__ == "__main__":
    out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "src", "dsp_taps.h")  # also holds the PIE tables
    designs = {r2: design(r2) for r2 in DESIGNS}
    for r2, (q, fp, fst) in designs.items():
        report(r2, q, fp, fst)
    emit(out, designs)
    print("wrote", os.path.normpath(out))
