/* ESP-IDF configuration for the SDK sources compiled into this image. */
#pragma once

#define CONFIG_IDF_TARGET_ESP32S3 1
#define CONFIG_IDF_TARGET "esp32s3"
#define CONFIG_XTAL_FREQ 40
#define CONFIG_XTAL_FREQ_40 1
#define CONFIG_MMU_PAGE_SIZE 0x10000
#define CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ 240
#define CONFIG_ESP32S3_REV_MIN_FULL 0
#define CONFIG_ESP32S3_REV_MAX_FULL 99
#define CONFIG_ESP_PHY_MAX_TX_POWER 20
#define CONFIG_ESP_PHY_MAX_WIFI_TX_POWER 20
#define CONFIG_ESP_PHY_ENABLE_USB 1
#define CONFIG_ESP_ROM_HAS_CRC_LE 1
#define CONFIG_ESP_ROM_HAS_CRC_BE 1
#define CONFIG_LIBC_NEWLIB 1
#define CONFIG_LOG_DEFAULT_LEVEL 0
#define CONFIG_LOG_MAXIMUM_LEVEL 0
#define CONFIG_LOG_VERSION 1
#define CONFIG_LOG_VERSION_1 1
#define CONFIG_BOOTLOADER_LOG_LEVEL 0
#define CONFIG_BOOTLOADER_LOG_VERSION 1
